### ISSUE TITLE
Grafana dashboard for RedisCDC

### ISSUE THREAD

**Issue by bjbredis** [RedisLabs-Field-Engineering/RedisCDC#3]
If there is an example dashboard for RedisCDC then it's json definition should be provided in this repo.

**Comment by viragtripathi** [comment]
There is a [sample dashboard](https://github.com/RedisLabs-Field-Engineering/RedisCDC/blob/master/Connectors/mssql/demo/RedisCDC_MSSQL_Connector.json) using grafana redis-datasource and it is available under [demo](https://github.com/RedisLabs-Field-Engineering/RedisCDC/tree/master/Connectors/mssql/demo) folder. This dashboard is built with Metrics captured by emp table changed data events and also provides metrics for the target redis database.
